library game_demo;
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'dart:ui' as ui;

part 'level.dart';
part 'pet.dart';
part 'variables.dart';
part 'scoreCount.dart';
part 'saveScore.dart';
part 'restoreScore.dart';
part 'start_screen.dart';
part 'changeLevel.dart';
part 'map.dart';
part 'level2.dart';
part 'level3.dart';
part 'shop.dart';
part 'logic.dart';